# -*- coding: utf-8 -*-
"""64160234_1. Maximum number[cs11].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aZdVJTfnI0g9rcZB_oFsY_OPmOlHlVsf
"""

max = 0
num = int(input())
while num > 0:
  if num > max :
    max = num
  num = int(input())
print(max)