# -*- coding: utf-8 -*-
"""64160234_Odd and even number[cs12].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hmj8GuR7J_crUo7GvHd1Tuk6UgRU7Pao
"""

num = int(input())
even = 0
odd = 0
while 0 <= num<= 100:
  if num % 2 == 0:
    even += 1
  else:
    odd += 1
  num = int(input())
print(even)
print(odd)