# -*- coding: utf-8 -*-
"""64160234_Number of Fat and Thin[cs13].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qGusTwp9lCh4J7TDOtuEFbAx9bUy3SHv
"""

weight = int(input())
fat = 0
thin = 0
while weight >= 0:
  if weight > 60:
    fat += 1
  else:
    thin += 1
  weight = int(input())
print(fat)
print(thin)