# -*- coding: utf-8 -*-
"""Calculator[cs08]_64160234.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14uOUNmTMJgxQgzPmz5Wja0Ccchhr5cXK
"""

import math
num1 = int(input())
num2 = float(input())
num3 = float(input())
if num1 == 1:
  num2 = num2 + num3
  print(round(num2,2))
elif num1 == 2:
  num2 = num2 - num3
  print(round(num2,2))
elif num1 == 3:
  num2 = num2*num3
  print(round(num2,2))
elif num1 == 4:
  num2 = num2/num3
  print(round(num2,2))
else:
  print('Incorrect Symbol')