# -*- coding: utf-8 -*-
"""Lists Value Adding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VPBIBeJJipEqiSyC35E6-oyzMfvWNlgN
"""

def aflist ():
  for i in range(n):
    if nlist[i] >= 10:
      nlist[i] += 1
    else:
      nlist[i] -= 1
    print(nlist[i],end=' ')
    
#main
n = int(input())
nlist = [ 0 for i in range(n)]
for i in range(n):
  nlist[i] = int(input())
print('Before data')
for i in range(n):
  print(nlist[i],end=' ')
print()
print('After data')
aflist()