# -*- coding: utf-8 -*-
"""OX Reverses Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NfP1hi2gaR1jxlOy0H0_bS5EfpGQTczs
"""

def String_Input(row,column):
  tic = [[' ' for j in range(column)] for i in range(row)]
  for i in range(row):
    for j in range(column):
      tic[i][j] = input().strip()
  return tic

def String_Show(row,column):
  print('Normal')
  for i in range(row):
    for j in range(column):
      print(tic[i][j],end=' ')


def String_Transpose(row,column):
  print('Reverses')
  for i in range(row):
    for j in range(column):
      if tic[i][j] == 'x':
        tic[i][j] = 'o'
      else:
        tic[i][j] = 'x'
      print(tic[i][j],end=' ')


#main
row = int(input())
column = int(input())
String_Input(row,column)
String_Show(row,column)
String_Transpose(row,column)