# -*- coding: utf-8 -*-
"""Row and Column Number [cs16].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gDF9QyGXNg7CWTt9AdWLWMlE672Kusgq
"""

#Row and Column Number [cs16]
m = int(input())
n = int(input())
for row in range(m):
    print('')
    for colum in range(1,n+1):
        print(colum,end=' ')