# -*- coding: utf-8 -*-
"""Square Number [cs15].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HCMTyNbpuW5YJqBYxe4LAuasQxuK1NaY
"""

#Square Number [cs15]
m1 = int(input())
n1= int(input())
for row in range(m1):
  print('')
  for colum in range(n1):
    print(row+1,end=' ')