# -*- coding: utf-8 -*-
"""Star Symbol [cs17].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QbpdndhCqGKwaBliEWlcl6BtW9nihn6D
"""

#Star Symbol [cs17]
num = int(input())
for n in range(1,num+1):
  if n%5 == 0: 
    print(end='X')
    continue
  print(end='*')