# -*- coding: utf-8 -*-
"""ThemePark[cs10]_64160234.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/140nEIUWnCcRMm8aCJ71JVDZuuafxErpi
"""

man = int(input())
age = int(input())
if man == 1:
  if age < 15 :
    print('150 Bath')
  else:
    print('350 Bath')
elif man == 2:
  if age < 15:
    print('80 Bath')
  else:
    print('200 Bath')