# -*- coding: utf-8 -*-
"""Transpose Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11WpNBzpsEcOnXzHpichenas62Utget-v
"""

def Matrix_Input(row,column):
  matrix = [[0 for j in range(column)]for i in range(row)]
  for i in range(row):
    for j in range(column):
      matrix[i][j] = int(input())
  return matrix
    
def Matrix_Show(matrix,row,column):
  for i in range(row):
    for j in range(column):
      print(matrix[i][j],end=' ')
    print()
  
def Matrix_Transpose(matrix,row,column):
  for j in range(column):
    for i in range(row):
      print(matrix[i][j],end=' ')
    print()
  
#main program
row = int(input())
column =int(input())
matrix=Matrix_Input(row,column)
print('Matrix Normal')
Matrix_Show(matrix,row,column)
print('Matrix Transpose')
Matrix_Transpose(matrix,row,column)