# -*- coding: utf-8 -*-
"""Transpose Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11WpNBzpsEcOnXzHpichenas62Utget-v
"""

def Matrix_Input(sum,row,column):
  a = [[0 for j in range(column)] for i in range(row)]
  for i in range(row):
    for j in range(column):
      a[i][j] = int(input())
  return a

def Maxtrix_Show(sum,row,column):
  print('Matrix Normal')
  for i in range(row):
    for j in range(column):
      print(a[i][j],end= ' ')
    print()

def Maxtrix_Transpose(sum,row,column):
  print('Matrix Transpose')
  for j in range(column):
    for i in range(row):
      print(a[i][j],end=' ')
    print()

#main
row = int(input())
column = int(input())
Matrix_Input(sum,row,column)
Maxtrix_Show(sum,row,column)
Maxtrix_Transpose(sum,row,column)