# -*- coding: utf-8 -*-
"""Zero Number[cs14].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15TiqJMm5nqq6kCn9qGUx5mjPHDFzzj9x
"""

#Zero Number[cs14]
num = int(input())
zero = 0
for i in range(num):
  num = int(input())
  if num == 0:
    zero += 1
print(zero)